# @package _global_

defaults:
  - _self_
  - data: vehicle_data # choose datamodule with `test_dataloader()` for evaluation
  - model: vehicle
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: "[val, mobilenetv2]"

# passing checkpoint path is necessary for evaluation
ckpt_path: "logs/train/runs/2024-01-31_18-20-41/checkpoints/epoch_079.ckpt"
